#!/bin/bash
# spec/20 Phase-9 §step 2 — build the qdistro-print guest disk image.
#
# Produces /var/lib/libvirt/images/qdistro-print-base.qcow2 with:
#   - openSUSE Tumbleweed Minimal-VM Cloud base
#   - cups + cups-filters preinstalled (no GUI)
#   - cups-browsed + cups-driverd
#   - cupsd configured to listen on AF_VSOCK port 631 (replacing the
#     default localhost:631 listener so the host's qdistro-print-proxy
#     reaches it via vsock without any TCP/IP exposure)
#   - qemu-guest-agent service enabled for guest-exec (host-side
#     job-control + USB-hot-plug companion commands)
#   - cloud-init stub configured for libvirt's per-VM seed iso
#   - a small /etc/cups/cupsd.conf override + systemd drop-in
#
# Linux-only per spec/00. Reuses the tier-5-style cache pattern: the
# Tumbleweed cloud qcow2 is downloaded once into ~/.cache/qdistro/ and
# customized into the print-base.
#
# Run on the host:
#   sudo ./build-print-image.sh
#
# Build cost: one-time download of ~400MB (or zero if the tier-5 cache
# already has it), then ~30s of customization (cups package install).
#
# Bats coverage: pwd-print-recall.bats `phase9-print-vm-build` skips gracefully
# when the base image is absent — so this isn't a hard prereq for the
# rest of the suite.
set -euo pipefail

usage() {
    cat <<'EOF'
qdistro-print guest image builder.

Usage:
  build-print-image.sh [--force] [--mirror URL] [--dest PATH] [--cache PATH]

Options:
  --force        Rebuild even if dest already exists.
  --mirror URL   Override Tumbleweed-Minimal-VM download URL.
  --dest PATH    Output path
                 (default /var/lib/libvirt/images/qdistro-print-base.qcow2).
  --cache PATH   Cache dir for the upstream qcow2
                 (default $HOME/.cache/qdistro). Reuses the tier-5
                 base cache if present.

Reqs:
  virt-customize, qemu-img, wget. zypper install libguestfs guestfs-tools qemu-tools.
EOF
}

FORCE=0
DEST=/var/lib/libvirt/images/qdistro-print-base.qcow2
CACHE_DIR="${HOME}/.cache/qdistro"
MIRROR=https://download.opensuse.org/tumbleweed/appliances/openSUSE-Tumbleweed-Minimal-VM.x86_64-Cloud.qcow2

while [ $# -gt 0 ]; do
    case "$1" in
        -h|--help)   usage; exit 0;;
        --force)     FORCE=1; shift;;
        --mirror)    shift; MIRROR="${1:?--mirror requires URL}"; shift;;
        --dest)      shift; DEST="${1:?--dest requires PATH}"; shift;;
        --cache)     shift; CACHE_DIR="${1:?--cache requires PATH}"; shift;;
        *) echo "unknown arg: $1" >&2; usage >&2; exit 2;;
    esac
done

DEST_DIR="$(dirname "$DEST")"
# Need root only when the chosen destination is somewhere a normal
# user can't write — typically /var/lib/libvirt/images/. With --dest
# pointing at a user-owned path (e.g. ~/.local/share/libvirt/images/)
# the build runs unprivileged, which is the path the admin app's P2
# integration smoke uses.
if ! { [ -d "$DEST_DIR" ] && [ -w "$DEST_DIR" ]; } \
   && [ ! -w "$(dirname "$DEST_DIR")" ] \
   && [ "$(id -u)" -ne 0 ]; then
    echo "[print-build] must run as root or pass --dest under a writable dir" >&2
    echo "[print-build] (default writes $DEST; override with --dest)" >&2
    exit 2
fi
for tool in virt-customize qemu-img wget; do
    command -v "$tool" >/dev/null || { echo "[print-build] missing: $tool" >&2; exit 2; }
done

if [ -f "$DEST" ] && [ "$FORCE" != "1" ]; then
    echo "[print-build] $DEST already exists; use --force to rebuild" >&2
    exit 0
fi

install -d -m 0755 "$CACHE_DIR"
CACHE_QCOW="$CACHE_DIR/tier5-base-cloud.qcow2"
if [ ! -f "$CACHE_QCOW" ]; then
    echo "[print-build] downloading base image to $CACHE_QCOW..."
    wget -q --show-progress -O "$CACHE_QCOW.partial" "$MIRROR" || {
        rm -f "$CACHE_QCOW.partial"
        echo "[print-build] FAIL: download from $MIRROR" >&2
        exit 3
    }
    mv "$CACHE_QCOW.partial" "$CACHE_QCOW"
fi
WORK="$(mktemp -d /tmp/print-build.XXXXXX)"
trap 'rm -rf "$WORK"' EXIT
BASE_QCOW="$WORK/base.qcow2"
cp --reflink=auto "$CACHE_QCOW" "$BASE_QCOW"

# Stage the cupsd override. cupsd doesn't natively listen on
# AF_VSOCK — we wrap it with a small socat bridge that forwards
# vsock:631 → unix:/run/cups/cups.sock. The drop-in starts the
# bridge under a separate unit so cupsd itself stays unmodified
# (and any cupsd security update keeps working).
CONF_DIR="$WORK/qdistro-conf"
mkdir -p "$CONF_DIR/etc/cups" \
         "$CONF_DIR/etc/systemd/system" \
         "$CONF_DIR/usr/local/bin"

cat >"$CONF_DIR/etc/cups/cupsd.conf" <<'CONF'
# qdistro-print cupsd.conf — minimal. Listens on the standard local
# UNIX socket only (no TCP); the vsock bridge unit forwards from
# CID-any:631 to this socket.
#
# Generated by spec/20 Phase-9 §step 2 build-print-image.sh.

LogLevel warn
PageLogFormat
MaxLogSize 0

# Lock down the admin web UI to localhost only — admin uses the
# qdistro panel, NOT the cupsd web UI.
Listen /run/cups/cups.sock
WebInterface No
DefaultAuthType Basic

<Location />
  Order allow,deny
  Allow from localhost
</Location>
<Location /admin>
  AuthType Default
  Require user @SYSTEM
  Order allow,deny
  Allow from localhost
</Location>

# Don't auto-discover network printers from cupsd's own browse
# subsystem — discovery runs through cups-browsed (separate unit)
# whose config the host renders from broker qdistro.print.discover.*
# rules via qdistro-print-allowlist.
BrowsePolling
BrowseLocalProtocols
BrowseRemoteProtocols

# spec/20 §step 2 priority #6: job-size + page-count + queue caps.
# Defaults are conservative — admin overrides via `cupsctl` or by
# editing /etc/cups/cupsd.conf directly inside the VM. Tunables are
# drawn from cups-files.conf(5)/cupsd.conf(5). Values:
#   MaxJobs               — total queued jobs (active + held).
#   MaxJobsPerUser        — per-uid cap; foils a runaway flatpak.
#   MaxJobsPerPrinter     — per-destination cap.
#   MaxRequestSize        — single-request body cap (default 0 = no
#                           limit). 64MB covers a long PDF; tightens
#                           denial-of-storage attacks.
#   PreserveJobHistory    — keep finished job rows for the audit log.
#   PreserveJobFiles      — drop job spool files after completion to
#                           reduce on-disk leak surface.
MaxJobs               500
MaxJobsPerUser         50
MaxJobsPerPrinter     200
MaxRequestSize  67108864
PreserveJobHistory     Yes
PreserveJobFiles        No
CONF

# spec/20 §step 2 priority #5: default-deny cups-browsed.conf. The
# host's qdistro-print-allowlist renders + pushes a per-deployment
# allowlist; until admin authors qdistro.print.discover.<host> rules,
# the VM announces nothing.
mkdir -p "$CONF_DIR/etc"
cat >"$CONF_DIR/etc/cups-browsed.conf" <<'BCONF'
# qdistro-print cups-browsed.conf — default-deny.
# Generated by build-print-image.sh; replaced live by
# `qdistro-print-allowlist apply --vm <name>` from the host.
BrowseProtocols cups dnssd
BrowseLocalProtocols cups dnssd
BrowseRemoteProtocols cups dnssd
BrowseAllow none
BCONF

cat >"$CONF_DIR/etc/systemd/system/qdistro-print-vsock.service" <<'UNIT'
[Unit]
Description=qdistro print: vsock bridge to local cupsd
After=cups.socket cups.service
BindsTo=cups.socket

[Service]
Type=simple
# Listen on AF_VSOCK port 631; forward to the cupsd UNIX socket.
# socat handles per-connection fork; concurrent jobs supported.
ExecStart=/usr/bin/socat VSOCK-LISTEN:631,reuseaddr,fork UNIX-CONNECT:/run/cups/cups.sock
Restart=on-failure
RestartSec=2
User=root
Group=lp

[Install]
WantedBy=multi-user.target
UNIT

cat >"$CONF_DIR/usr/local/bin/qdistro-print-job-control" <<'JC'
#!/bin/bash
# qdistro-print-job-control — minimal job control helper invoked by
# the host via guest-exec. Subcommands:
#   list                 — print active jobs (lpstat -o)
#   cancel <jobid>       — cancel one job
#   purge                — purge all jobs (lprm -a)
case "${1:-}" in
    list)   exec lpstat -o ;;
    cancel) shift; exec cancel -a "${1:?usage: $0 cancel <jobid>}" ;;
    purge)  exec cancel -a -x ;;
    *) echo "usage: $0 {list|cancel <jobid>|purge}" >&2; exit 2 ;;
esac
JC
chmod +x "$CONF_DIR/usr/local/bin/qdistro-print-job-control"

# Priority #6: per-queue page-count cap helper. CUPS doesn't expose
# a global "max pages per job" knob; the equivalent is per-printer
# `job-page-limit-default`. The wrapper accepts a queue name + page
# count and runs the right `lpadmin -o` invocation. Admin runs it
# from the host via guest-exec (or directly if shelled into the VM).
cat >"$CONF_DIR/usr/local/bin/qdistro-print-set-page-limit" <<'PL'
#!/bin/bash
# qdistro-print-set-page-limit <queue> <pages>
#   Sets the default + maximum job-page-limit on <queue>. Pages is an
#   integer; CUPS treats negative as "unlimited" but admin should pass
#   a positive value or "0" to disable the cap.
set -euo pipefail
queue="${1:?usage: $0 <queue> <pages>}"
pages="${2:?usage: $0 <queue> <pages>}"
if ! [[ "$pages" =~ ^[0-9]+$ ]]; then
    echo "[set-page-limit] pages must be a non-negative integer: $pages" >&2
    exit 2
fi
if ! lpstat -p "$queue" >/dev/null 2>&1; then
    echo "[set-page-limit] queue not found: $queue" >&2
    exit 3
fi
lpadmin -p "$queue" \
    -o "job-page-limit-default=$pages" \
    -o "job-page-limit-supported=$pages"
echo "[set-page-limit] $queue page-limit=$pages"
PL
chmod +x "$CONF_DIR/usr/local/bin/qdistro-print-set-page-limit"

echo "[print-build] customizing..."
virt-customize -a "$BASE_QCOW" \
    --install cups,cups-filters,cups-browsed,cups-pdf,socat,qemu-guest-agent \
    --copy-in "$CONF_DIR/etc/cups/cupsd.conf:/etc/cups/" \
    --copy-in "$CONF_DIR/etc/cups-browsed.conf:/etc/" \
    --copy-in "$CONF_DIR/etc/systemd/system/qdistro-print-vsock.service:/etc/systemd/system/" \
    --copy-in "$CONF_DIR/usr/local/bin/qdistro-print-job-control:/usr/local/bin/" \
    --copy-in "$CONF_DIR/usr/local/bin/qdistro-print-set-page-limit:/usr/local/bin/" \
    --run-command 'systemctl enable qemu-guest-agent.service' \
    --run-command 'systemctl enable cups.socket' \
    --run-command 'systemctl enable qdistro-print-vsock.service' \
    --run-command 'systemctl enable serial-getty@ttyS0.service' \
    --run-command 'systemctl mask cloud-init-local.service cloud-init.service cloud-config.service cloud-final.service cloud-init.target 2>/dev/null || true' \
    --run-command 'echo "qdistro-print" >/etc/hostname' \
    --run-command "sed -i 's/\\bquiet\\b//g; s/GRUB_CMDLINE_LINUX_DEFAULT=\"\\(.*\\)\"/GRUB_CMDLINE_LINUX_DEFAULT=\"\\1 earlyprintk=ttyS0,115200\"/' /etc/default/grub" \
    --run-command 'grub2-mkconfig -o /boot/grub2/grub.cfg' \
    --root-password 'password:Pa_ssw0rd45' \
    --run-command 'modprobe vsock; modprobe vhost_vsock || true' \
    >/dev/null

echo "[print-build] sparsifying..."
virt-sparsify --in-place "$BASE_QCOW" 2>/dev/null || true

install -d "$(dirname "$DEST")"
mv "$BASE_QCOW" "$DEST"
chmod 0644 "$DEST"
# chown to root only when we have permission. Under sudo / direct
# root invocation this normalises ownership for /var/lib/libvirt/.
# When --dest points at a user-owned dir (admin running unprivileged
# for the integration smoke), keep ownership as the invoking user.
if [ "$(id -u)" -eq 0 ]; then
    chown root:root "$DEST"
fi

echo "[print-build] done: $DEST"
ls -lh "$DEST"
