# This file has been autogenerated by the pywayland scanner

# Copyright © 2026 qdistro contributors
# SPDX-License-Identifier: MIT

from .qdwin_locker_surface_v1 import QdwinLockerSurfaceV1  # noqa: F401
from .qdwin_locker_v1 import QdwinLockerV1  # noqa: F401
