# This file has been autogenerated by the pywayland scanner

# Copyright © 2026 qdistro contributors
# SPDX-License-Identifier: MIT

from __future__ import annotations

from pywayland.protocol_core import (
    Argument,
    ArgumentType,
    Global,
    Interface,
    Proxy,
    Resource,
)


class QdwinLockerSurfaceV1(Interface):
    """Handle to a previously-attached lock surface

    Created by `:func:`QdwinLockerV1.attach_lock_surface()
    <pywayland.protocol.qdwin_locker_v1.QdwinLockerV1.attach_lock_surface>``.
    Destroying this object dismisses the lock surface; if the compositor is
    currently locked, the screen goes black until a fresh attach_lock_surface
    fires.
    """

    name = "qdwin_locker_surface_v1"
    version = 1


class QdwinLockerSurfaceV1Proxy(Proxy[QdwinLockerSurfaceV1]):
    interface = QdwinLockerSurfaceV1

    @QdwinLockerSurfaceV1.request()
    def destroy(self) -> None:
        """Dismiss the lock surface
        """
        self._marshal(0)
        self._destroy()

    @QdwinLockerSurfaceV1.request(
        Argument(ArgumentType.Uint),
    )
    def ack_configure(self, serial: int) -> None:
        """Ack the most recent configure

        :param serial:
        :type serial:
            `ArgumentType.Uint`
        """
        self._marshal(1, serial)


class QdwinLockerSurfaceV1Resource(Resource):
    interface = QdwinLockerSurfaceV1

    @QdwinLockerSurfaceV1.event(
        Argument(ArgumentType.Uint),
        Argument(ArgumentType.Uint),
        Argument(ArgumentType.Uint),
    )
    def configure(self, width: int, height: int, serial: int) -> None:
        """Output geometry hint

        Tells the locker the dimensions it should commit a buffer at to cover
        every output. Re-fires on output hot-plug or rotation.

        :param width:
        :type width:
            `ArgumentType.Uint`
        :param height:
        :type height:
            `ArgumentType.Uint`
        :param serial:
        :type serial:
            `ArgumentType.Uint`
        """
        self._post_event(0, width, height, serial)


class QdwinLockerSurfaceV1Global(Global):
    interface = QdwinLockerSurfaceV1


QdwinLockerSurfaceV1._gen_c()
QdwinLockerSurfaceV1.proxy_class = QdwinLockerSurfaceV1Proxy
QdwinLockerSurfaceV1.resource_class = QdwinLockerSurfaceV1Resource
QdwinLockerSurfaceV1.global_class = QdwinLockerSurfaceV1Global
