# This file has been autogenerated by the pywayland scanner

# Copyright © 2026 qdistro contributors
# SPDX-License-Identifier: MIT

from __future__ import annotations

import enum

from pywayland.protocol.wayland import WlSurface
from pywayland.protocol_core import (
    Argument,
    ArgumentType,
    Global,
    Interface,
    Proxy,
    Resource,
)

from .qdwin_locker_surface_v1 import QdwinLockerSurfaceV1


class QdwinLockerV1(Interface):
    """The qdwin locker attach point

    The locker binds this global once and holds it for the lifetime of its
    process. qdwin rejects a second bind from the same client. If a new locker
    comes up while the old one is still bound, qdwin destroys the old binding
    (the old process is considered dead — only one locker may exist at a time).

    Bootstrap: after `bind_as_locker`, qdwin accepts `set_locked(1)`
    immediately. If the Qt lock toplevel has not mapped yet, qdwin hides the
    normal desktop and shows a black screen until that toplevel appears, then
    promotes it to the LOCK layer.

    If the locker process dies while the compositor is in locked state, qdwin
    keeps the screen black and refuses input until a replacement locker binds.
    Admin's compositor is the trusted computing base; a missing locker is fail-
    safe (locked), not fail-open.
    """

    name = "qdwin_locker_v1"
    version = 1

    class error(enum.IntEnum):
        role = 0
        already_bound = 1
        no_surface = 2
        invalid_reason = 3
        not_bound = 4


class QdwinLockerV1Proxy(Proxy[QdwinLockerV1]):
    interface = QdwinLockerV1

    @QdwinLockerV1.request()
    def bind_as_locker(self) -> None:
        """Claim the locker role

        The locker announces that it is ready to receive lock-trigger events
        and to drive lock state. Must be the first request on the interface.
        qdwin replies with `ready` once it has confirmed the peer credentials
        and registered the binding.
        """
        self._marshal(0)

    @QdwinLockerV1.request(
        Argument(ArgumentType.NewId, interface=QdwinLockerSurfaceV1),
        Argument(ArgumentType.Object, interface=WlSurface),
    )
    def attach_lock_surface(self, surface: WlSurface) -> Proxy[QdwinLockerSurfaceV1]:
        """Install the lock overlay

        Legacy explicit lock-surface attach. Current qdlocker does not use this
        request; qdwin instead promotes qdlocker's real Qt xdg_toplevel to the
        compositor LOCK layer. This request is retained for compatibility with
        older lockers and tests.

        The surface must not have a role yet. After attach, it has the implicit
        "lock surface" role; any :func:`WlSurface.commit()
        <pywayland.protocol.wayland.WlSurface.commit>` triggers a frame on the
        LOCK layer.

        :param surface:
        :type surface:
            :class:`~pywayland.protocol.wayland.WlSurface`
        :returns:
            :class:`~pywayland.protocol.qdwin_locker_v1.QdwinLockerSurfaceV1`
        """
        id = self._marshal_constructor(1, QdwinLockerSurfaceV1, surface)
        return id

    @QdwinLockerV1.request(
        Argument(ArgumentType.Uint),
    )
    def set_locked(self, locked: int) -> None:
        """Transition compositor lock state

        `locked=1` → compositor enters the locked state: normal desktop layers
        are hidden, the lock layer remains visible, and input is delivered only
        to the locker via `overlay_key`. qdwin promotes the authorized locker's
        Qt toplevel to the lock layer when it maps. If it is not mapped yet,
        the screen stays black.

        `locked=0` → unlocks; user surfaces resume rendering. The locker is
        expected to call this only after a successful authentication.

        Compositor emits `locked_changed(locked)` to the shell on
        qdwin_shell_v1 after the transition completes, and emits the equivalent
        `locked_changed` event on this interface to the locker.

        Older qdwin builds failed with `no_surface` if no explicit lock surface
        was attached. Current qdwin accepts the request and waits for the real
        locker toplevel.

        :param locked:
        :type locked:
            `ArgumentType.Uint`
        """
        self._marshal(2, locked)

    @QdwinLockerV1.request(
        Argument(ArgumentType.Uint),
    )
    def lock_acknowledged(self, reason: int) -> None:
        """Ack a lock_requested event

        Tells the compositor the locker has handled (or deliberately ignored) a
        `lock_requested` event. Used for tests and for deciding whether the
        compositor should escalate (e.g. drop to a black screen if the locker
        fails to lock within a reasonable window after suspend).

        :param reason:
            must match the most recent lock_requested.reason
        :type reason:
            `ArgumentType.Uint`
        """
        self._marshal(3, reason)


class QdwinLockerV1Resource(Resource):
    interface = QdwinLockerV1

    @QdwinLockerV1.event(
        Argument(ArgumentType.Uint),
    )
    def ready(self, initially_locked: int) -> None:
        """Locker binding accepted

        Sent after `bind_as_locker` succeeds. If the compositor is already
        locked, the locker should show its Qt lock window and wait for the user
        to authenticate.

        :param initially_locked:
            1 if the compositor is currently locked, 0 otherwise
        :type initially_locked:
            `ArgumentType.Uint`
        """
        self._post_event(0, initially_locked)

    @QdwinLockerV1.event(
        Argument(ArgumentType.Uint),
    )
    def locked_changed(self, locked: int) -> None:
        """Compositor entered or left locked state

        Mirror of qdwin_shell_v1.locked_changed for the locker. Fires on every
        transition, including transitions the locker did not request (e.g. the
        compositor's fail-safe black screen when the bound locker process dies
        while locked).

        :param locked:
        :type locked:
            `ArgumentType.Uint`
        """
        self._post_event(1, locked)

    @QdwinLockerV1.event(
        Argument(ArgumentType.Uint),
    )
    def lock_requested(self, reason: int) -> None:
        """Compositor relays a lock trigger to the locker

        The compositor relays a lock trigger to the locker. `reason` names
        which of the sessions.md §"Lock triggers" caused it:

          reason = 0  idle     — ext-idle-notify-v1 timeout   reason = 1  lid
        — systemd-logind lid close   reason = 2  suspend  — prepare-for-sleep
        reason = 3  manual   — Ctrl+Alt+L global hotkey or admin
        panel "Lock now"

        Implementation note (current qdwin): the compositor only observes and
        emits `reason = 3` (the Ctrl+Alt+L hotkey). The locker sources the
        other triggers itself, NOT via this event: idle from its own idle
        timer, and lid/suspend by subscribing directly to systemd-logind
        (`Session.Lock` for lid, `PrepareForSleep` for suspend). Reasons 0/1/2
        are reserved here so the wire format stays stable if a future qdwin
        observes them directly; today they are not sent.

        The locker decides whether to call `set_locked(1)` (it usually does
        immediately, but may delay if a fingerprint verification is already in
        progress).

        :param reason:
        :type reason:
            `ArgumentType.Uint`
        """
        self._post_event(2, reason)

    @QdwinLockerV1.event(
        Argument(ArgumentType.Uint),
        Argument(ArgumentType.String),
    )
    def overlay_key(self, sym: int, utf8: str) -> None:
        """Key forwarded while locked

        While the compositor is locked, qdwin installs a keyboard grab and
        forwards each pressed key to the locker here. Identical wire format to
        qdwin_shell_v1.overlay_key (since v17) for the role=2 (locker) value,
        but delivered on the locker's connection so the shell cannot observe
        lock-time keystrokes — i.e. the password the user types never reaches
        the shell process.

        `sym` is the xkb keysym; `utf8` is the printable character (or "" if
        non-printable). The locker prefers utf8 when non-empty and falls back
        to `sym` for control keys (Escape, Return, BackSpace, Tab).

        Only PRESSED transitions are sent. Releases are absorbed by the grab.

        :param sym:
            xkb keysym (XKB_KEY_* / xkbcommon-keysyms.h)
        :type sym:
            `ArgumentType.Uint`
        :param utf8:
            UTF-8 for printable keys, '' otherwise
        :type utf8:
            `ArgumentType.String`
        """
        self._post_event(3, sym, utf8)


class QdwinLockerV1Global(Global):
    interface = QdwinLockerV1


QdwinLockerV1._gen_c()
QdwinLockerV1.proxy_class = QdwinLockerV1Proxy
QdwinLockerV1.resource_class = QdwinLockerV1Resource
QdwinLockerV1.global_class = QdwinLockerV1Global
