# This file has been autogenerated by the pywayland scanner

# Copyright © 2026 qdistro contributors
# SPDX-License-Identifier: MIT

from __future__ import annotations

import enum

from pywayland.protocol_core import (
    Argument,
    ArgumentType,
    Global,
    Interface,
    Proxy,
    Resource,
)

from pywayland.protocol.wayland import WlSurface
from .qdwin_locker_surface_v1 import QdwinLockerSurfaceV1


class QdwinLockerV1(Interface):
    """The qdwin locker attach point

    The locker binds this global once and holds it for the lifetime of its
    process. qdwin rejects a second bind from the same client. If a new locker
    comes up while the old one is still bound, qdwin destroys the old binding
    (the old process is considered dead — only one locker may exist at a time).

    Bootstrap: until the locker has sent `bind_as_locker` and attached a lock
    surface, qdwin treats `set_locked` requests as no-ops. The compositor
    starts in locked state by default (see sessions.md §"Admin logout /
    compositor crash") and waits for the locker to attach its surface before
    showing anything.

    If the locker process dies while the compositor is in locked state, qdwin
    keeps the screen black and refuses input until a replacement locker binds.
    Admin's compositor is the trusted computing base; a missing locker is fail-
    safe (locked), not fail-open.
    """

    name = "qdwin_locker_v1"
    version = 1

    class error(enum.IntEnum):
        role = 0
        already_bound = 1
        no_surface = 2
        invalid_reason = 3
        not_bound = 4


class QdwinLockerV1Proxy(Proxy[QdwinLockerV1]):
    interface = QdwinLockerV1

    @QdwinLockerV1.request()
    def bind_as_locker(self) -> None:
        """Claim the locker role

        The locker announces that it is ready to receive lock-trigger events
        and to drive lock state. Must be the first request on the interface.
        qdwin replies with `ready` once it has confirmed the peer credentials
        and registered the binding.
        """
        self._marshal(0)

    @QdwinLockerV1.request(
        Argument(ArgumentType.NewId, interface=QdwinLockerSurfaceV1),
        Argument(ArgumentType.Object, interface=WlSurface),
    )
    def attach_lock_surface(self, surface: WlSurface) -> Proxy[QdwinLockerSurfaceV1]:
        """Install the lock overlay

        Places `surface` on the compositor LOCK layer, covering every output.
        The surface is not yet "live" — the lock state is still driven by
        `set_locked`. Multiple lock surfaces are not allowed; a second attach
        replaces the first and dismisses the prior surface.

        The surface must not have a role yet. After attach, it has the implicit
        "lock surface" role; any :func:`WlSurface.commit()
        <pywayland.protocol.wayland.WlSurface.commit>` triggers a frame on the
        LOCK layer.

        :param surface:
        :type surface:
            :class:`~pywayland.protocol.wayland.WlSurface`
        :returns:
            :class:`~pywayland.protocol.qdwin_locker_v1.QdwinLockerSurfaceV1`
        """
        id = self._marshal_constructor(1, QdwinLockerSurfaceV1, surface)
        return id

    @QdwinLockerV1.request(
        Argument(ArgumentType.Uint),
    )
    def set_locked(self, locked: int) -> None:
        """Transition compositor lock state

        `locked=1` → compositor enters the locked state: the lock surface (from
        attach_lock_surface) is the only thing composited; user-session
        surfaces stop rendering; input is delivered only to the locker via
        `overlay_key`.

        `locked=0` → unlocks; user surfaces resume rendering. The locker is
        expected to call this only after a successful authentication.

        Compositor emits `locked_changed(locked)` to the shell on
        qdwin_shell_v1 after the transition completes, and emits the equivalent
        `locked_changed` event on this interface to the locker.

        Fails with `no_surface` if no lock surface is attached.

        :param locked:
        :type locked:
            `ArgumentType.Uint`
        """
        self._marshal(2, locked)

    @QdwinLockerV1.request(
        Argument(ArgumentType.Uint),
    )
    def lock_acknowledged(self, reason: int) -> None:
        """Ack a lock_requested event

        Tells the compositor the locker has handled (or deliberately ignored) a
        `lock_requested` event. Used for tests and for deciding whether the
        compositor should escalate (e.g. drop to a black screen if the locker
        fails to lock within a reasonable window after suspend).

        :param reason:
            must match the most recent lock_requested.reason
        :type reason:
            `ArgumentType.Uint`
        """
        self._marshal(3, reason)


class QdwinLockerV1Resource(Resource):
    interface = QdwinLockerV1

    @QdwinLockerV1.event(
        Argument(ArgumentType.Uint),
    )
    def ready(self, initially_locked: int) -> None:
        """Locker binding accepted

        Sent after `bind_as_locker` succeeds. The locker should now attach its
        lock surface and (if the compositor is already locked) wait for the
        user to authenticate.

        :param initially_locked:
            1 if the compositor is currently locked, 0 otherwise
        :type initially_locked:
            `ArgumentType.Uint`
        """
        self._post_event(0, initially_locked)

    @QdwinLockerV1.event(
        Argument(ArgumentType.Uint),
    )
    def locked_changed(self, locked: int) -> None:
        """Compositor entered or left locked state

        Mirror of qdwin_shell_v1.locked_changed for the locker. Fires on every
        transition, including transitions the locker did not request (e.g. the
        lid-close path inside the compositor).

        :param locked:
        :type locked:
            `ArgumentType.Uint`
        """
        self._post_event(1, locked)

    @QdwinLockerV1.event(
        Argument(ArgumentType.Uint),
    )
    def lock_requested(self, reason: int) -> None:
        """User pressed the manual-lock keybinding or lid closed

        Aggregates the triggers in sessions.md §"Lock triggers" that the
        compositor observes directly:

          reason = 0  idle     — ext-idle-notify-v1 timeout   reason = 1  lid
        — systemd-logind lid close   reason = 2  suspend  — prepare-for-sleep
        reason = 3  manual   — Ctrl+Alt+L global hotkey or admin
        panel "Lock now"

        The locker decides whether to call `set_locked(1)` (it usually does
        immediately, but may delay if a fingerprint verification is already in
        progress).

        :param reason:
        :type reason:
            `ArgumentType.Uint`
        """
        self._post_event(2, reason)

    @QdwinLockerV1.event(
        Argument(ArgumentType.Uint),
        Argument(ArgumentType.String),
    )
    def overlay_key(self, sym: int, utf8: str) -> None:
        """Key forwarded while locked

        While the lock surface is attached and the compositor is locked, qdwin
        installs a keyboard grab and forwards each pressed key to the locker
        here. Identical wire format to qdwin_shell_v1.overlay_key (since v17)
        for the role=2 (locker) value, but delivered on the locker's connection
        so the shell cannot observe lock-time keystrokes — i.e. the password
        the user types never reaches the shell process.

        `sym` is the xkb keysym; `utf8` is the printable character (or "" if
        non-printable). The locker prefers utf8 when non-empty and falls back
        to `sym` for control keys (Escape, Return, BackSpace, Tab).

        Only PRESSED transitions are sent. Releases are absorbed by the grab.

        :param sym:
            xkb keysym (XKB_KEY_* / xkbcommon-keysyms.h)
        :type sym:
            `ArgumentType.Uint`
        :param utf8:
            UTF-8 for printable keys, '' otherwise
        :type utf8:
            `ArgumentType.String`
        """
        self._post_event(3, sym, utf8)


class QdwinLockerV1Global(Global):
    interface = QdwinLockerV1


QdwinLockerV1._gen_c()
QdwinLockerV1.proxy_class = QdwinLockerV1Proxy
QdwinLockerV1.resource_class = QdwinLockerV1Resource
QdwinLockerV1.global_class = QdwinLockerV1Global
