"""qdistro presentation snapshot: stdlib core.

Importing this package must not construct a QApplication, load Qt, import
dbus, read HOME, or start a thread. The Qt adapter lives in
``qdistro_presentation.qt`` and is imported explicitly by GUI apps.
"""

from .model import (
    BASE_POINT_SIZE_DEFAULT,
    COLOR_KEYS,
    CONTRAST_TEXT,
    DEFAULT_DARK_COLORS,
    SCHEMA_VERSION,
    THEME_MODES,
    Colors,
    Fonts,
    LocalOverrides,
    Metrics,
    Motion,
    PresentationSnapshot,
    ResolvedPresentation,
    SnapshotError,
    SnapshotPathError,
    animation_ms,
    changed_fields,
    contrast_ratio,
    example_snapshot,
    generation_for_content,
    input_radius_px,
    normalize_producer,
    parse_local_overrides,
    parse_snapshot,
    parse_snapshot_bytes,
    parse_snapshot_text,
    resolve_presentation,
    with_generation,
)
from .paths import (
    DEPLOYMENT_META,
    ENV_OVERRIDE,
    MANAGED_DIR,
    MANAGED_FILE,
    ResolvedPath,
    load_snapshot,
    resolve_snapshot_path,
)
from .publish import WriteResult, write_disabled_envelope, write_snapshot

__all__ = [
    "BASE_POINT_SIZE_DEFAULT",
    "COLOR_KEYS",
    "CONTRAST_TEXT",
    "DEFAULT_DARK_COLORS",
    "DEPLOYMENT_META",
    "ENV_OVERRIDE",
    "MANAGED_DIR",
    "MANAGED_FILE",
    "SCHEMA_VERSION",
    "THEME_MODES",
    "Colors",
    "Fonts",
    "LocalOverrides",
    "Metrics",
    "Motion",
    "PresentationSnapshot",
    "ResolvedPath",
    "ResolvedPresentation",
    "SnapshotError",
    "SnapshotPathError",
    "WriteResult",
    "animation_ms",
    "changed_fields",
    "contrast_ratio",
    "example_snapshot",
    "generation_for_content",
    "input_radius_px",
    "load_snapshot",
    "normalize_producer",
    "parse_local_overrides",
    "parse_snapshot",
    "parse_snapshot_bytes",
    "parse_snapshot_text",
    "resolve_presentation",
    "resolve_snapshot_path",
    "with_generation",
    "write_disabled_envelope",
    "write_snapshot",
]
