ARG BASE_IMAGE
FROM ${BASE_IMAGE}
ARG SNAPSHOT
COPY container-native-deps.sh /usr/local/bin/container-native-deps.sh
RUN QDISTRO_SUBSTRATE_SNAPSHOT="$SNAPSHOT" /bin/bash /usr/local/bin/container-native-deps.sh
LABEL org.qdistro.test-snapshot="$SNAPSHOT"
