import QtQuick
import QtQuick.Layouts
import Quickshell
import qs.Commons
import qs.Services.Qdistro
import qs.Widgets

// "Sandboxed VM apps" — teardown policy for tier-5 (per-app VM) silos.
//
// Tier-5 apps each run in a disposable nested VM. qdistro's host-side wrapper
// (spawn-tier5.sh) reads its teardown policy from a small sectioned config file
// in the admin's home; this tab is the GUI for that file. Settings live in
// Settings.data.vmApps (global defaults) + Settings.data.vmApps.perApp (per-app
// overrides keyed by catalogue appId). Whenever they change we regenerate
// ~/.config/qdistro/tier5-lifecycle.conf:
//
//   SHUTDOWN_METHOD=…          (global defaults — the implicit top section)
//   …
//   [app:tier5/firefox]        (only for apps with an override enabled)
//   SHUTDOWN_METHOD=…
//
// The wrapper resolves per value: env > [app:<appId>] > global > built-in, and
// re-validates/clamps everything, so this is a convenience surface, not a trust
// boundary. The file is GUI-owned: it is rewritten wholesale and atomically.
ColumnLayout {
  id: root
  spacing: Style.marginL
  Layout.fillWidth: true

  readonly property var methodModel: [
    { "key": "graceful", "name": I18n.tr("panels.vmApps.method-graceful") },
    { "key": "force",    "name": I18n.tr("panels.vmApps.method-force") }
  ]

  // ── policy helpers ────────────────────────────────────────────────────
  function _method(v) { return v === "force" ? "force" : "graceful"; }
  function _int(v, lo, hi) {
    var n = parseInt(v);
    if (isNaN(n)) n = lo;
    return Math.max(lo, Math.min(hi, n));
  }
  // Same shape the wrapper validates (catalogue-style key); defence in depth.
  function _validKey(k) {
    return (typeof k === "string") && /^[A-Za-z0-9][A-Za-z0-9._/-]{0,127}$/.test(k);
  }

  function overrideFor(appId) {
    var m = Settings.data.vmApps.perApp || ({});
    return m[appId] || null;
  }
  function isOverridden(appId) {
    var ov = overrideFor(appId);
    return !!ov && ov.enabled === true;
  }
  function _freshOverride() {
    var g = Settings.data.vmApps;
    return {
      "enabled": true,
      "shutdownMethod": g.shutdownMethod,
      "shutdownGraceSecs": g.shutdownGraceSecs,
      "idleShutdownMinutes": g.idleShutdownMinutes,
      "lowMemoryMb": g.lowMemoryMb
    };
  }
  function setOverrideEnabled(appId, on) {
    var m = JSON.parse(JSON.stringify(Settings.data.vmApps.perApp || ({})));
    if (on) {
      if (!m[appId]) m[appId] = _freshOverride();
      else m[appId].enabled = true;
    } else if (m[appId]) {
      m[appId].enabled = false;
    }
    Settings.data.vmApps.perApp = m;
    root.writeLifecycleConf();
  }
  function setOverrideField(appId, field, value) {
    var m = JSON.parse(JSON.stringify(Settings.data.vmApps.perApp || ({})));
    if (!m[appId]) m[appId] = _freshOverride();
    m[appId][field] = value;
    m[appId].enabled = true;
    Settings.data.vmApps.perApp = m;
    root.writeLifecycleConf();
  }

  // Regenerate the whole config file atomically (temp -> chmod 600 -> rename).
  // appIds are validated and every value is coerced to the wrapper's accepted
  // range, so `body` carries no free-form text; the quoted heredoc keeps it
  // literal. The file is fully qdshell-owned — hand edits may be overwritten.
  function writeLifecycleConf() {
    var g = Settings.data.vmApps;
    var lines = [
      "# Generated by qdshell — \"Sandboxed VM apps\" settings.",
      "# Read by qdistro's tier-5 wrapper (spawn-tier5.sh), which re-validates",
      "# and clamps every value. Manual edits may be overwritten by qdshell.",
      "SHUTDOWN_METHOD=" + _method(g.shutdownMethod),
      "SHUTDOWN_GRACE_SECS=" + _int(g.shutdownGraceSecs, 0, 300),
      "IDLE_SHUTDOWN_SECS=" + (_int(g.idleShutdownMinutes, 0, 1440) * 60),
      "LOWMEM_MB=" + _int(g.lowMemoryMb, 0, 65536)
    ];
    var m = g.perApp || ({});
    for (var appId in m) {
      var ov = m[appId];
      if (!ov || ov.enabled !== true || !_validKey(appId)) continue;
      lines.push("");
      lines.push("[app:" + appId + "]");
      lines.push("SHUTDOWN_METHOD=" + _method(ov.shutdownMethod));
      lines.push("SHUTDOWN_GRACE_SECS=" + _int(ov.shutdownGraceSecs, 0, 300));
      lines.push("IDLE_SHUTDOWN_SECS=" + (_int(ov.idleShutdownMinutes, 0, 1440) * 60));
      lines.push("LOWMEM_MB=" + _int(ov.lowMemoryMb, 0, 65536));
    }
    var body = lines.join("\n") + "\n";
    Quickshell.execDetached(["sh", "-c",
      "d=\"$HOME/.config/qdistro\"; f=\"$d/tier5-lifecycle.conf\"; t=\"$f.tmp.$$\"; "
      + "mkdir -p \"$d\" && cat > \"$t\" <<'QDLIFECYCLEEOF'\n"
      + body
      + "QDLIFECYCLEEOF\n"
      + "chmod 600 \"$t\" && mv -f \"$t\" \"$f\""]);
  }

  // Keep the file in sync with current settings whenever the tab is shown.
  Component.onCompleted: writeLifecycleConf()

  NText {
    Layout.fillWidth: true
    text: I18n.tr("panels.vmApps.intro")
    wrapMode: Text.WordWrap
    color: Color.mOnSurfaceVariant
  }

  // ═══════════════════════════════════════════════════════════════════
  // Global defaults — Shutdown
  // ═══════════════════════════════════════════════════════════════════
  NText {
    text: I18n.tr("panels.vmApps.section-shutdown")
    pointSize: Style.fontSizeM
    font.weight: Style.fontWeightBold
    color: Color.mPrimary
  }

  NComboBox {
    Layout.fillWidth: true
    label: I18n.tr("panels.vmApps.method-label")
    description: I18n.tr("panels.vmApps.method-description")
    model: root.methodModel
    currentKey: Settings.data.vmApps.shutdownMethod
    defaultValue: Settings.getDefaultValue("vmApps.shutdownMethod")
    onSelected: key => {
      Settings.data.vmApps.shutdownMethod = key;
      root.writeLifecycleConf();
    }
  }

  NSpinBox {
    Layout.fillWidth: true
    visible: Settings.data.vmApps.shutdownMethod !== "force"
    label: I18n.tr("panels.vmApps.grace-label")
    description: I18n.tr("panels.vmApps.grace-description")
    minimum: 0
    maximum: 300
    stepSize: 5
    suffix: " s"
    value: Settings.data.vmApps.shutdownGraceSecs
    defaultValue: Settings.getDefaultValue("vmApps.shutdownGraceSecs")
    onValueChanged: {
      Settings.data.vmApps.shutdownGraceSecs = value;
      root.writeLifecycleConf();
    }
  }

  // ═══════════════════════════════════════════════════════════════════
  // Global defaults — Idle
  // ═══════════════════════════════════════════════════════════════════
  NText {
    text: I18n.tr("panels.vmApps.section-idle")
    pointSize: Style.fontSizeM
    font.weight: Style.fontWeightBold
    color: Color.mPrimary
  }

  NSpinBox {
    Layout.fillWidth: true
    label: I18n.tr("panels.vmApps.idle-label")
    description: I18n.tr("panels.vmApps.idle-description")
    minimum: 0
    maximum: 1440
    stepSize: 1
    suffix: " min"
    value: Settings.data.vmApps.idleShutdownMinutes
    defaultValue: Settings.getDefaultValue("vmApps.idleShutdownMinutes")
    onValueChanged: {
      Settings.data.vmApps.idleShutdownMinutes = value;
      root.writeLifecycleConf();
    }
  }

  // ═══════════════════════════════════════════════════════════════════
  // Global defaults — Memory
  // ═══════════════════════════════════════════════════════════════════
  NText {
    text: I18n.tr("panels.vmApps.section-memory")
    pointSize: Style.fontSizeM
    font.weight: Style.fontWeightBold
    color: Color.mPrimary
  }

  NSpinBox {
    Layout.fillWidth: true
    label: I18n.tr("panels.vmApps.lowmem-label")
    description: I18n.tr("panels.vmApps.lowmem-description")
    minimum: 0
    maximum: 65536
    stepSize: 256
    suffix: " MB"
    value: Settings.data.vmApps.lowMemoryMb
    defaultValue: Settings.getDefaultValue("vmApps.lowMemoryMb")
    onValueChanged: {
      Settings.data.vmApps.lowMemoryMb = value;
      root.writeLifecycleConf();
    }
  }

  // ═══════════════════════════════════════════════════════════════════
  // Per-app overrides
  // ═══════════════════════════════════════════════════════════════════
  NText {
    text: I18n.tr("panels.vmApps.section-perapp")
    pointSize: Style.fontSizeM
    font.weight: Style.fontWeightBold
    color: Color.mPrimary
  }
  NText {
    Layout.fillWidth: true
    text: I18n.tr("panels.vmApps.perapp-intro")
    wrapMode: Text.WordWrap
    color: Color.mOnSurfaceVariant
  }

  Repeater {
    model: VMApps.catalogue
    delegate: ColumnLayout {
      id: appRow
      required property var modelData
      readonly property string appId: modelData.appId
      readonly property var ov: root.overrideFor(appId)
      readonly property bool overridden: root.isOverridden(appId)
      Layout.fillWidth: true
      Layout.topMargin: Style.marginS
      spacing: Style.marginXS

      NToggle {
        Layout.fillWidth: true
        label: appRow.modelData.name
        description: I18n.tr("panels.vmApps.override-label")
        checked: appRow.overridden
        onToggled: checked => root.setOverrideEnabled(appRow.appId, checked)
      }

      NComboBox {
        Layout.fillWidth: true
        Layout.leftMargin: Style.marginL
        visible: appRow.overridden
        label: I18n.tr("panels.vmApps.method-label")
        model: root.methodModel
        currentKey: appRow.ov ? appRow.ov.shutdownMethod : "graceful"
        onSelected: key => root.setOverrideField(appRow.appId, "shutdownMethod", key)
      }
      NSpinBox {
        Layout.fillWidth: true
        Layout.leftMargin: Style.marginL
        visible: appRow.overridden && (appRow.ov ? appRow.ov.shutdownMethod : "graceful") !== "force"
        label: I18n.tr("panels.vmApps.grace-label")
        minimum: 0
        maximum: 300
        stepSize: 5
        suffix: " s"
        value: appRow.ov ? appRow.ov.shutdownGraceSecs : 15
        onValueChanged: {
          if (appRow.overridden)
            root.setOverrideField(appRow.appId, "shutdownGraceSecs", value);
        }
      }
      NSpinBox {
        Layout.fillWidth: true
        Layout.leftMargin: Style.marginL
        visible: appRow.overridden
        label: I18n.tr("panels.vmApps.idle-label")
        minimum: 0
        maximum: 1440
        stepSize: 1
        suffix: " min"
        value: appRow.ov ? appRow.ov.idleShutdownMinutes : 0
        onValueChanged: {
          if (appRow.overridden)
            root.setOverrideField(appRow.appId, "idleShutdownMinutes", value);
        }
      }
      NSpinBox {
        Layout.fillWidth: true
        Layout.leftMargin: Style.marginL
        visible: appRow.overridden
        label: I18n.tr("panels.vmApps.lowmem-label")
        minimum: 0
        maximum: 65536
        stepSize: 256
        suffix: " MB"
        value: appRow.ov ? appRow.ov.lowMemoryMb : 0
        onValueChanged: {
          if (appRow.overridden)
            root.setOverrideField(appRow.appId, "lowMemoryMb", value);
        }
      }
    }
  }
}
