"""Pod-app launch routing (tracker J12 Fix A).

A launcher click on a container app used to fork spawn-tier2 DIRECTLY from
qdshell — the unprivileged admin session. With no root launcher parent
spawn-tier2 cannot run qdistro-secctx-exec as a trusted child, so the app's
Wayland connection carried no wp_security_context_v1 at all (nothing could tell
the compositor which silo/app the window belonged to), and on a hardened
profile spawn-tier2 refused the launch outright — clicking a pod app did
nothing whatsoever on daily-driver/release.

The click now goes through SessionManager1.LaunchPodApp, which starts
qdistro-podapp@<launch-token>.service (User=root, hands spawn-tier2
TIER2_ROOT_LAUNCHER=1). These tests pin the parts that are easy to regress
silently:

  - the launch env stanza the root helper will `.`-source, and its quoting;
  - the launch token: generated by the DAEMON (never caller-supplied), of the
    exact shape the shell's secctx-instance correlator filters on, and unique
    per call;
  - input validation, because every field crosses into a root-sourced env file
    and then into podman/spawn-tier2 argv;
  - fail-closed cleanup, so a unit that did not start leaves no spent stanza;
  - the shipped source of the helper/unit/shell caller, so a refactor cannot
    quietly reintroduce the un-tagged direct-fork path.

The end-to-end wire tag itself needs a real session and is proven by the VM
lane (permissions-gui/18 + the tier2 secctx wiretag probes).
"""
from __future__ import annotations

import json
import re
import shlex
from pathlib import Path

import pytest
from qdistro_session_manager import (
    PODAPP_LAUNCHER_FMT,
    BadArgument,
    SessionError,
    _SiloStore,
)

from test_session_manager import _FakeOps

_REPO = Path(__file__).resolve().parents[2]
_LAUNCH = _REPO / "session_manager" / "qdistro-podapp-launch"
_STOP = _REPO / "session_manager" / "qdistro-podapp-stop"
_UNIT = _REPO / "session_manager" / "qdistro-podapp@.service"
_SPAWN = _REPO / "tier2" / "spawn-tier2.sh"
_DBUS_CONF = _REPO / "session_manager" / "org.qdistro.SessionManager1.conf"
_INSTALL = _REPO / "scripts" / "install" / "install-session-manager.sh"
_PODAPPS_QML = (_REPO.parent / "qdshell" / "Services" / "Qdistro"
                / "PodApps.qml")

_TOKEN_RE = re.compile(r"^[0-9a-f]{32}$")


@pytest.fixture
def ops() -> _FakeOps:
    return _FakeOps()


@pytest.fixture
def store(ops: _FakeOps, tmp_path: Path) -> _SiloStore:
    return _SiloStore(ops, config_path=tmp_path / "silos.yaml")


def _env(ops: _FakeOps, token: str) -> dict[str, str]:
    """Parse the stanza the root helper will source (KEY='VALUE' lines)."""
    out: dict[str, str] = {}
    for line in ops.podapp_launch_envs[token].splitlines():
        if not line.strip():
            continue
        k, _, v = line.partition("=")
        out[k] = " ".join(shlex.split(v))
    return out


# ---- the launch itself ----------------------------------------------------

def test_launch_starts_the_root_launcher_unit(store, ops):
    """The whole point of J12 Fix A: a click starts the User=root unit rather
    than forking spawn-tier2 in the caller's unprivileged session."""
    token = store.launch_podapp("podapp-term", "weston-terminal",
                                json.dumps(["/usr/bin/weston-terminal"]))
    assert _TOKEN_RE.match(token), token
    assert ops.systemctl_calls == [
        ("start", PODAPP_LAUNCHER_FMT.format(token=token))]
    # The unit instance IS the token — not the container name. Hex needs no
    # systemd escaping, and two clicks on one app never collide on an instance.
    assert token in PODAPP_LAUNCHER_FMT.format(token=token)


def test_launch_env_carries_the_full_stanza(store, ops):
    token = store.launch_podapp("podapp-term", "weston-terminal",
                                json.dumps(["/usr/bin/weston-terminal", "-e",
                                            "top"]))
    env = _env(ops, token)
    assert env["QD_LAUNCH_TOKEN"] == token
    assert env["QD_CONTAINER"] == "podapp-term"
    assert env["QD_WORKLOAD"] == "weston-terminal"
    assert json.loads(env["QD_APP_ARGV_JSON"]) == [
        "/usr/bin/weston-terminal", "-e", "top"]
    # Pod apps keep the pre-J12 posture: no network unless that becomes an
    # explicit policy decision.
    assert env["TIER2_NETWORK"] == "none"


def test_env_token_matches_the_unit_instance(store, ops):
    """The helper cross-checks these two and refuses a mismatch, so a
    divergence here would break every launch — pin them equal."""
    token = store.launch_podapp("c", "w", "[]")
    assert _env(ops, token)["QD_LAUNCH_TOKEN"] == token
    assert ops.systemctl_calls[0][1] == PODAPP_LAUNCHER_FMT.format(token=token)


def test_tokens_are_unique_per_launch(store):
    tokens = {store.launch_podapp("c", "w", "[]") for _ in range(25)}
    assert len(tokens) == 25


def test_argv_quoting_survives_the_env_round_trip(store, ops):
    """The stanza is `.`-sourced by bash, so a value containing quotes/spaces
    must come back byte-identical — otherwise the app launches with mangled
    arguments (or the source breaks outright)."""
    argv = ["/bin/sh", "-c", "echo 'it\"s here'; ls $HOME", "a b\tc"]
    token = store.launch_podapp("c", "w", json.dumps(argv))
    assert json.loads(_env(ops, token)["QD_APP_ARGV_JSON"]) == argv


def test_empty_argv_is_allowed(store, ops):
    """The helper falls back to the workload binary name; an empty list must
    not be an error at this layer."""
    token = store.launch_podapp("c", "weston-terminal", "[]")
    assert json.loads(_env(ops, token)["QD_APP_ARGV_JSON"]) == []


# ---- validation -----------------------------------------------------------

@pytest.mark.parametrize("container", [
    "", "../escape", "a/../b", "-leading-dash", "semi;colon", "sp ace",
    "dollar$sign", "nl\nine", "x" * 129,
])
def test_unsafe_container_is_refused(store, ops, container):
    with pytest.raises(BadArgument):
        store.launch_podapp(container, "weston-terminal", "[]")
    assert ops.systemctl_calls == []
    assert ops.podapp_launch_envs == {}


@pytest.mark.parametrize("workload", ["", "../escape", "semi;colon", "sp ace"])
def test_unsafe_workload_is_refused(store, ops, workload):
    with pytest.raises(BadArgument):
        store.launch_podapp("podapp-term", workload, "[]")
    assert ops.systemctl_calls == []


@pytest.mark.parametrize("argv_json", [
    "not json",
    '{"not": "a list"}',
    '[1, 2, 3]',
    '["ok", null]',
])
def test_bad_argv_json_is_refused(store, ops, argv_json):
    with pytest.raises(BadArgument):
        store.launch_podapp("podapp-term", "weston-terminal", argv_json)
    assert ops.systemctl_calls == []


def test_argv_entry_with_newline_is_refused(store, ops):
    """Single-line argv is an API policy of this surface (the stanza we write
    is one line per value). The helper itself transports newlines fine — it
    splits on NUL — so this is policy, not a transport requirement."""
    with pytest.raises(BadArgument):
        store.launch_podapp("podapp-term", "weston-terminal",
                            json.dumps(["ok", "two\nargs"]))
    assert ops.systemctl_calls == []


def test_argv_entry_with_nul_is_refused(store, ops):
    """NUL is the helper's argv separator, and json.loads decodes the \\u0000
    escape into a real one — an accepted entry would split into TWO arguments
    at exec time. It cannot appear in a real exec'd argv element either, so
    reject it rather than re-encode."""
    with pytest.raises(BadArgument):
        store.launch_podapp("podapp-term", "weston-terminal", '["a\\u0000b"]')
    assert ops.systemctl_calls == []


def test_oversized_argv_is_refused(store, ops):
    with pytest.raises(BadArgument):
        store.launch_podapp("podapp-term", "weston-terminal",
                            json.dumps(["a"] * 65))
    with pytest.raises(BadArgument):
        store.launch_podapp("podapp-term", "weston-terminal",
                            json.dumps(["x" * 4097]))
    assert ops.systemctl_calls == []


# ---- failure handling -----------------------------------------------------

def test_failed_unit_start_removes_the_stanza(store, ops):
    """A stanza for a unit that never started is a spent token nobody will
    clean up (the unit's own ExecStopPost is what normally removes it)."""
    def _boom(unit: str) -> None:
        raise OSError("systemctl start failed (simulated)")
    ops.systemctl_start = _boom
    with pytest.raises(SessionError):
        store.launch_podapp("podapp-term", "weston-terminal", "[]")
    assert ops.podapp_launch_envs == {}


def test_failed_env_write_does_not_start_the_unit(store, ops):
    def _boom(token: str, content: str):
        raise OSError("write failed (simulated)")
    ops.write_podapp_launch_env = _boom
    with pytest.raises(SessionError):
        store.launch_podapp("podapp-term", "weston-terminal", "[]")
    assert ops.systemctl_calls == []


# ---- shipped-source invariants -------------------------------------------
#
# The pieces below only exist on a real system (root unit, D-Bus, a session).
# Pin them in the shipped source so a refactor cannot quietly reintroduce the
# un-tagged path this task removed.

def test_helper_hands_spawn_the_root_launcher_topology():
    src = _LAUNCH.read_text()
    assert "TIER2_ROOT_LAUNCHER=1" in src
    assert 'TIER2_ADMIN_UID="$ADMIN_UID"' in src
    assert 'TIER2_LAUNCH_TOKEN="$TOKEN"' in src, \
        "the helper must pre-commit the token the daemon returned to the shell"
    assert "exec env -i" in src, \
        "an ambient environment must not be able to weaken the sandbox posture"
    # The privilege-weakening knobs must never be re-added to the exec env.
    assert "TIER2_ALLOW_PRIVESC=" not in src
    assert "TIER2_KEEP_CAPS=" not in src
    assert "TIER2_SECCOMP_PROFILE=" not in src
    # Fail-closed admin resolution: missing user / uid 0 / not 1000.
    assert "does not exist" in src and "exit 6" in src
    assert 'ADMIN_UID" != "0"' in src
    assert 'ADMIN_UID" = "1000"' in src
    # The spawn must run UNDER those guards (exec is the last statement).
    assert src.index('ADMIN_UID="$(id -u') < src.rindex("exec env")


def test_helper_argv_split_preserves_empty_elements():
    """`mapfile -t` on a newline-joined argv silently drops empty elements —
    and a trailing empty one entirely — so the app would be launched with a
    DIFFERENT argv than the caller asked for. The split must be NUL-separated,
    the one byte an exec'd argv element cannot contain (and the daemon's
    validator rejects, including the \\u0000 JSON escape)."""
    src = _LAUNCH.read_text()
    assert "mapfile -d '' -t APP_ARGV" in src, \
        "argv must be split on NUL, not newlines"
    assert '\\n".join(argv)' not in src, \
        "the newline join drops empty argv elements"
    # Run the actual splitter out of the shipped source rather than a copy, so
    # this cannot pass against a stale duplicate of the pipeline.
    start = src.index("mapfile -d '' -t APP_ARGV")
    snippet = src[start:src.index("')", start) + 2]
    script = (f'export QD_WORKLOAD=weston-terminal\n{snippet}\n'
              'printf "%s\\n" "${#APP_ARGV[@]}"\n'
              'printf "[%s]" "${APP_ARGV[@]}"\n')
    import subprocess
    out = subprocess.run(
        ["bash", "-c", script], capture_output=True, text=True,
        env={"PATH": "/usr/bin:/bin",
             "QD_APP_ARGV_JSON": json.dumps(["a", "", "b", ""])})
    assert out.returncode == 0, out.stderr
    count, rendered = out.stdout.split("\n", 1)
    assert count == "4", f"empty argv elements were dropped: {out.stdout!r}"
    assert rendered.strip() == "[a][][b][]"


def test_helper_argv_split_fails_closed_when_the_splitter_dies(tmp_path) -> None:
    """`mapfile` reads a PROCESS SUBSTITUTION, so neither `pipefail` nor
    mapfile's own status notices a failing splitter — without the `wait "$!"`
    the helper would carry on with an EMPTY argv and exec anyway. Pin the
    fail-closed status against the shipped source."""
    src = _LAUNCH.read_text()
    start = src.index("mapfile -d '' -t APP_ARGV")
    end = src.index('wait "$!"', start) + len('wait "$!"')
    snippet = src[start:end]
    assert 'wait "$!"' in snippet, "the splitter's status must be waited on"
    farm = tmp_path / "failbin"
    farm.mkdir()
    (farm / "python3").write_text("#!/bin/bash\nexit 42\n")
    (farm / "python3").chmod(0o755)
    import subprocess
    script = ("set -euo pipefail\nexport QD_WORKLOAD=weston-terminal\n"
              f"{snippet}\n" 'echo REACHED_EXEC\n')
    out = subprocess.run(
        ["bash", "-c", script], capture_output=True, text=True,
        env={"PATH": f"{farm}:/usr/bin:/bin", "QD_APP_ARGV_JSON": "[]"},
        timeout=30)
    assert out.returncode == 42, (out.returncode, out.stdout, out.stderr)
    assert "REACHED_EXEC" not in out.stdout


def test_helper_verifies_the_env_file_before_sourcing_it_as_root():
    """The helper runs as root and `.`-sources the stanza — that is root code
    execution, so ownership/mode must be checked BEFORE the source."""
    src = _LAUNCH.read_text()
    assert "require_trusted_env" in src
    assert src.index('require_trusted_env "$ENV_FILE"') < src.index('. "$ENV_FILE"')


def test_helper_validates_the_instance_token():
    """The instance name becomes a file path, and it must match the stanza —
    otherwise we would launch off some other click's stanza."""
    src = _LAUNCH.read_text()
    assert '^[0-9a-f]{32}$' in src
    assert 'QD_LAUNCH_TOKEN:-}" = "$TOKEN"' in src


def test_stop_helper_drops_to_admin_and_fails_closed():
    src = _STOP.read_text()
    assert "runuser -u" in src
    assert 'ADMIN_UID" = "0"' in src or 'ADMIN_UID" != "0"' in src
    assert "podman" in src and "stop" in src
    assert '^[0-9a-f]{32}$' in src


def test_unit_runs_as_root_and_stops_the_container():
    unit = _UNIT.read_text()
    assert "User=root" in unit, \
        "root is required only as spawn-tier2's trusted launcher PARENT"
    assert "ExecStart=/usr/libexec/qdistro/qdistro-podapp-launch %i" in unit
    assert "ExecStop=-/usr/libexec/qdistro/qdistro-podapp-stop %i" in unit, \
        "rootless podman does not proxy SIGTERM; the container needs an " \
        "explicit admin-side stop or it outlives the unit"
    assert "Restart=no" in unit, \
        "a pod app the user closed must not be silently relaunched"
    assert "ExecStopPost=" in unit and "podapp-launch/%i.env" in unit


def test_spawn_accepts_a_precommitted_token_but_validates_it():
    """Under a unit, spawn-tier2's stdout is the journal — so the token has to
    travel the other way. It is the secctx instance-id and a directory name, so
    a malformed one must be refused rather than sanitised."""
    src = _SPAWN.read_text()
    # Anchor on the code, not the comment above it.
    idx = src.index('if [ -n "${TIER2_LAUNCH_TOKEN:-}" ]')
    window = src[idx:idx + 800]
    assert '^[0-9a-f]{32}$' in window
    assert "exit 2" in window
    # Absent the override we must still generate one.
    assert "gen_launch_token" in window


def test_dbus_policy_denies_launch_to_non_admin():
    conf = _DBUS_CONF.read_text()
    assert "LaunchPodApp" in conf, \
        "starting a User=root unit is an admin lifecycle op"
    deny = conf[conf.index('<policy context="default">'):]
    assert "LaunchPodApp" in deny


def test_installer_lands_the_unit_and_helpers():
    src = _INSTALL.read_text()
    assert "qdistro-podapp@.service" in src
    assert "qdistro-podapp-launch" in src
    assert "qdistro-podapp-stop" in src
    assert "-m 0755" in src


@pytest.mark.skipif(not _PODAPPS_QML.exists(),
                    reason="qdshell checkout not present next to qdistro")
def test_shell_no_longer_forks_the_spawn_helper():
    """The regression this task exists to prevent: a click that forks
    spawn-tier2 from the unprivileged session produces an un-tagged window in
    dev and no window at all on a hardened profile."""
    qml = _PODAPPS_QML.read_text()
    launch = qml[qml.index("function launch(row)"):]
    launch = launch[:launch.index("function _registerPlaceholder")]
    assert "qdistro-tier2-spawn" not in launch
    assert "spawn-tier2" not in launch
    assert "LaunchPodApp" in launch
    assert "gdbus" in launch
    # The placeholder must key on the token the daemon returned.
    assert "_registerPlaceholder" in launch
    assert "[0-9a-f]{32}" in launch
