#!/bin/bash
# Build the qdistro disk image with kiwi-ng.
#
# Output (todo/iso/13, Phase C of todo/iso/14):
#   $BUILD_DIR/qdistro.x86_64-<version>.raw          the 28 GiB raw kiwi built
#   $BUILD_DIR/bundle/qdistro-<version>-<snapshot>.raw.xz   the release artifact
#   $BUILD_DIR/bundle/qdistro-<version>-<snapshot>.raw.xz.sha256
#   (`xzcat <file> | dd of=/dev/sdX bs=4M conv=fsync` writes a bootable
#    stick; a VM boots the decompressed raw directly. No install ISO:
#    installiso="false" in config.xml.)
#
# <version> is config.xml's <version>; <snapshot> is the Tumbleweed snapshot
# id both repositories in config.xml are pinned to (snapshot_id below).
# The five source commits that went in are written by sync_sources into the
# overlay as root/root/qdistro-source-manifest and installed by config.sh as
# /etc/qdistro/release, together with version and snapshot.
#
# Requirements (Tumbleweed dev host):
#   sudo zypper in python3-kiwi kiwi-systemdeps qemu-x86 qemu-tools
#
# Usage:
#   sudo ./build.sh                  # full build (rsyncs sources, runs kiwi)
#   sudo ./build.sh --clean          # nuke build dir first
#   ./build.sh --test                # boot the resulting image in qemu
#   ./build.sh --sync-only           # only refresh root/root/qdistro-src
#   ./build.sh --no-sync             # sources already synced (build-in-vm.sh)
#   ./build.sh --snapshot-id         # print the pinned snapshot id and exit

set -euo pipefail

HERE="$(cd "$(dirname "$0")" && pwd)"
# $HERE is <repo>/image, so the sibling-repo root is two levels up, not one
# (iso/14 Phase A item 2). The one-level form predates the import of image/
# into the qdistro repo and made every in-repo build fail its sibling check.
SIBLINGS="$(cd "$HERE/../.." && pwd)"
# /tmp is a tmpfs on the build hosts; a kiwi run does not fit in RAM.
BUILD_DIR="${QDISTRO_BUILD_DIR:-/var/tmp/qdistro-build}"
SRC_OVERLAY="$HERE/root/root/qdistro-src"  # ends up at /root/qdistro-src in image
# Generated by sync_sources; lands at /root/qdistro-source-manifest in the
# chroot, where config.sh turns it into /etc/qdistro/release and removes it.
# Lives under root/root/ so it is gitignored with the synced sources.
MANIFEST="$HERE/root/root/qdistro-source-manifest"
SYNC_REPOS="qdistro qdwin qdshell qdgreeter qdlocker"

# snapshot_id: the Tumbleweed snapshot both repositories in config.xml are
# pinned to. config.xml is the only place the id is written (kiwi's parser
# rejects XML entities, so it cannot be spelled once); the two source paths
# must agree, and a build with a mismatched or unpinned pair is refused
# rather than silently mixing snapshots.
snapshot_id() {
    local ids n
    ids="$(sed -n 's|.*<source path="https://download.opensuse.org/history/\([0-9]\{8\}\)/tumbleweed/repo/[a-z-]*/"/>.*|\1|p' "$HERE/config.xml")"
    n="$(printf '%s\n' "$ids" | grep -c .)"
    if [ "$n" -ne 2 ]; then
        echo "[build] ERROR: config.xml must pin exactly two repositories to history/<YYYYMMDD>/ (found $n)" >&2
        return 2
    fi
    if [ "$(printf '%s\n' "$ids" | sort -u | wc -l)" -ne 1 ]; then
        echo "[build] ERROR: config.xml repositories pin different snapshots: $(printf '%s ' $ids)" >&2
        return 2
    fi
    printf '%s\n' "$ids" | head -n1
}

image_version() {
    sed -n 's|.*<version>\([0-9][0-9.]*\)</version>.*|\1|p' "$HERE/config.xml" | head -n1
}

# write_manifest: one line per synced repo -- name, commit, clean/DIRTY --
# plus the snapshot id, so a built artifact can be traced to five commits.
# build.sh strips .git during the sync, so this is the only moment the
# commits can be read. "DIRTY" alone cannot distinguish two uncommitted
# states on the same parent, so a dirty tree also records the sha256 of its
# diff against HEAD and the count of untracked files. A tree without .git
# (synced from a tarball) records "no-git": the build is not refused, but
# the image says so.
write_manifest() {
    local snap repo state
    snap="$(snapshot_id)" || exit 2
    {
        echo "SNAPSHOT=$snap"
        for repo in $SYNC_REPOS; do
            if [ -d "$SIBLINGS/$repo/.git" ]; then
                if git -C "$SIBLINGS/$repo" status --porcelain 2>/dev/null | grep -q .; then
                    state="DIRTY diff-sha256=$(git -C "$SIBLINGS/$repo" diff HEAD 2>/dev/null | sha256sum | cut -c1-16) untracked=$(git -C "$SIBLINGS/$repo" status --porcelain 2>/dev/null | grep -c '^??' || true)"
                else
                    state=clean
                fi
                # (grep -c exits 1 on a zero count; under set -e that would
                # abort the sync for a tree with tracked changes only.)
                printf 'SOURCE %s %s %s\n' "$repo" \
                    "$(git -C "$SIBLINGS/$repo" rev-parse HEAD 2>/dev/null || echo unknown)" "$state"
            else
                printf 'SOURCE %s no-git\n' "$repo"
            fi
        done
    } > "$MANIFEST"
    echo "[build] source manifest ($MANIFEST):"
    sed 's/^/  /' "$MANIFEST"
}

sync_sources() {
    install -d -m 0755 "$SRC_OVERLAY"
    # qdgreeter + qdlocker are part of the production boot/session path:
    # greetd execs /usr/bin/qdgreeter (greetd-config.toml) and the
    # qdwin-session.target Wants= qdlocker.service. config.sh pip-installs
    # both from this overlay, so they must be synced in (findings #16, #19).
    for repo in $SYNC_REPOS; do
        if [ ! -d "$SIBLINGS/$repo" ]; then
            echo "[build] ERROR: $SIBLINGS/$repo not found (sibling repo missing)" >&2
            exit 2
        fi
        echo "[build] rsyncing $repo -> $SRC_OVERLAY/$repo"
        # Leading slashes anchor these at the repo root: an unanchored
        # `ci/runs` would also drop an unrelated `anything/ci/runs`.
        #   /image/root/root — with the corrected $SIBLINGS the qdistro repo
        #     contains this very overlay, so an unfiltered sync copies the
        #     destination into itself.
        #   /image/logs — build logs, each holding the tarball of a previous
        #     run (which holds the run before it). Left in, they made the
        #     overlay 169 MB of stale nested tarballs and shipped them to
        #     /root/qdistro-src in the image, differing run to run.
        #   /ci/runs — gigabytes of untracked CI run artifacts in a working
        #     checkout; never part of the image.
        # Excluded paths are also protected from --delete, so debris left by
        # an earlier unfiltered sync would survive forever: clear it first.
        rm -rf "$SRC_OVERLAY/$repo/image/root/root" \
               "$SRC_OVERLAY/$repo/image/logs" \
               "$SRC_OVERLAY/$repo/ci/runs"
        # `build`, `node_modules`, `__pycache__` and `*.pyc` stay UNanchored on
        # purpose: they are build products at any depth (meson/cmake build
        # dirs, vendored JS). No tracked path in the five repos is named
        # `build` today, so nothing shipped is dropped by that.
        rsync -a --delete \
              --exclude=.git \
              --exclude=__pycache__ \
              --exclude='*.pyc' \
              --exclude=build \
              --exclude=node_modules \
              --exclude=/image/root/root \
              --exclude=/image/logs \
              --exclude=/ci/runs \
              "$SIBLINGS/$repo/" "$SRC_OVERLAY/$repo/"
    done
    echo "[build] source overlay sizes:"
    du -sh "$SRC_OVERLAY"/* 2>&1 | sed 's/^/  /'
    write_manifest
}

case "${1:-}" in
  --clean)
    rm -rf "$BUILD_DIR"
    rm -rf "$HERE/root/root"
    sync_sources
    ;;
  --sync-only)
    sync_sources
    exit 0
    ;;
  --no-sync)
    # Sources are already present (e.g. baked into a VM by build-in-vm.sh).
    # The manifest is written at sync time, on the host; without it the
    # image could not say what went in, so its absence is a build error.
    if [ ! -s "$MANIFEST" ]; then
        echo "[build] ERROR: --no-sync but no source manifest at $MANIFEST (run --sync-only first)" >&2
        exit 2
    fi
    ;;
  --snapshot-id)
    snapshot_id
    exit $?
    ;;
  --test)
    img=$(find "$BUILD_DIR" -maxdepth 1 -name '*.raw' 2>/dev/null | head -1)
    [ -n "$img" ] || { echo "no .raw image in $BUILD_DIR; run a build first" >&2; exit 1; }
    OVMF=""
    for c in /usr/share/qemu/ovmf-x86_64.bin /usr/share/qemu/ovmf-x86_64-code.bin /usr/share/OVMF/OVMF_CODE.fd; do
        [ -f "$c" ] && OVMF="$c" && break
    done
    [ -n "$OVMF" ] || { echo "no OVMF firmware found" >&2; exit 1; }
    exec qemu-system-x86_64 -enable-kvm -m 4096 -smp 2 \
      -bios "$OVMF" \
      -drive file="$img",format=raw,if=virtio \
      -netdev user,id=n0 -device virtio-net,netdev=n0
    ;;
  "")
    sync_sources
    ;;
  *)
    echo "unknown arg: $1" >&2
    exit 2
    ;;
esac

if [ "$EUID" -ne 0 ]; then
  echo "[build] build must run as root; re-exec with sudo" >&2
  exec sudo -E "$0" "$@"
fi

mkdir -p "$BUILD_DIR"
SNAPSHOT="$(snapshot_id)" || exit 2
VERSION="$(image_version)"
[ -n "$VERSION" ] || { echo "[build] ERROR: no <version> in config.xml" >&2; exit 2; }
if ! grep -q "^SNAPSHOT=$SNAPSHOT\$" "$MANIFEST"; then
    echo "[build] ERROR: manifest snapshot ($(sed -n 's/^SNAPSHOT=//p' "$MANIFEST")) != config.xml snapshot ($SNAPSHOT); re-sync" >&2
    exit 2
fi

echo "[build] kiwi-ng building OEM image $VERSION on Tumbleweed $SNAPSHOT -> $BUILD_DIR"
mkdir -p "$HERE/logs"
kiwi-ng --debug \
  --type oem \
  system build \
    --description "$HERE" \
    --target-dir "$BUILD_DIR" \
  2>&1 | tee "$HERE/logs/kiwi-build.log"
# `set -o pipefail` above: a kiwi failure is this script's failure.

# Release artifact. kiwi's `compressed` attribute is valid only for pxe/kis
# types (schema 8.4), so an OEM build cannot emit .raw.xz itself; `result
# bundle` copies the results under bundle/ (reflink/sparse cp), xz-compresses
# the raw with --threads=0 and writes a .sha256 of the compressed file. With
# bundle_format="%N-%v-%I" in config.xml the name is <name>-<version>-<id>;
# the id is the snapshot so the filename says what it was built on.
BUNDLE_DIR="$BUILD_DIR/bundle"
rm -rf "$BUNDLE_DIR"
echo "[build] bundling -> $BUNDLE_DIR (xz of the raw; several minutes)"
kiwi-ng result bundle \
    --target-dir "$BUILD_DIR" \
    --id "$SNAPSHOT" \
    --bundle-dir "$BUNDLE_DIR" \
  2>&1 | tee "$HERE/logs/kiwi-bundle.log"
XZ="$BUNDLE_DIR/qdistro-$VERSION-$SNAPSHOT.raw.xz"
[ -f "$XZ" ] || { echo "[build] ERROR: bundle did not produce $XZ" >&2; ls -l "$BUNDLE_DIR" >&2; exit 1; }
[ -f "$XZ.sha256" ] || { echo "[build] ERROR: bundle did not produce $XZ.sha256" >&2; exit 1; }

echo
echo "[build] artifacts:"
ls -lh "$BUILD_DIR" "$BUNDLE_DIR" | grep -E '\.(raw|iso|qcow2|xz|sha256)$' || true
