#!/bin/bash
# Build the qdistro disk image with kiwi-ng.
#
# Output (todo/iso/13, Phase C of todo/iso/14):
#   $BUILD_DIR/qdistro.x86_64-<version>.raw          the 28 GiB raw kiwi built
#   $BUILD_DIR/bundle/qdistro-<version>-<snapshot>.raw.xz   the release artifact
#   $BUILD_DIR/bundle/qdistro-<version>-<snapshot>.raw.xz.sha256
#   (`xzcat <file> | dd of=/dev/sdX bs=4M conv=fsync` writes a bootable
#    stick; a VM boots the decompressed raw directly. No install ISO:
#    installiso="false" in config.xml.)
#
# <version> is config.xml's <version>; <snapshot> is the Tumbleweed snapshot
# id both repositories in config.xml are pinned to (snapshot_id below).
# The five source commits that went in are written by sync_sources into the
# overlay as root/root/qdistro-source-manifest and installed by config.sh as
# /etc/qdistro/release, together with version and snapshot.
#
# Requirements (Tumbleweed dev host):
#   sudo zypper in python3-kiwi kiwi-systemdeps qemu-x86 qemu-tools
#
# Usage:
#   sudo ./build.sh                  # full build (rsyncs sources, runs kiwi)
#   sudo ./build.sh --clean          # nuke build dir first
#   ./build.sh --test                # boot the resulting image in qemu
#   ./build.sh --sync-only           # only refresh root/root/qdistro-src
#   ./build.sh --no-sync             # sources already synced (build-in-vm.sh)
#   ./build.sh --snapshot-id         # print the pinned snapshot id and exit

set -euo pipefail

HERE="$(cd "$(dirname "$0")" && pwd)"
# $HERE is <repo>/image. The monorepo root (qdistro content + the in-tree
# components qdwin/, qdshell/, qdgreeter/, qdlocker/, ...) is one level up,
# and that whole tree is what ships as /root/qdistro-src (O6).
REPO_ROOT="$(cd "$HERE/.." && pwd)"
# /tmp is a tmpfs on the build hosts; a kiwi run does not fit in RAM.
BUILD_DIR="${QDISTRO_BUILD_DIR:-/var/tmp/qdistro-build}"
SRC_OVERLAY="$HERE/root/root/qdistro-src"  # ends up at /root/qdistro-src in image
# Generated by sync_sources; lands at /root/qdistro-source-manifest in the
# chroot, where config.sh turns it into /etc/qdistro/release and removes it.
# Lives under root/root/ so it is gitignored with the synced sources.
MANIFEST="$HERE/root/root/qdistro-source-manifest"
# Components config.sh builds from the synced tree; checked for presence.
REQUIRED_COMPONENTS="qdwin qdshell qdgreeter qdlocker"

# snapshot_id: the Tumbleweed snapshot both repositories in config.xml are
# pinned to. config.xml is the only place the id is written (kiwi's parser
# rejects XML entities, so it cannot be spelled once); the two source paths
# must agree, and a build with a mismatched or unpinned pair is refused
# rather than silently mixing snapshots.
snapshot_id() {
    local ids n
    ids="$(sed -n 's|.*<source path="https://download.opensuse.org/history/\([0-9]\{8\}\)/tumbleweed/repo/[a-z-]*/"/>.*|\1|p' "$HERE/config.xml")"
    n="$(printf '%s\n' "$ids" | grep -c .)"
    if [ "$n" -ne 2 ]; then
        echo "[build] ERROR: config.xml must pin exactly two repositories to history/<YYYYMMDD>/ (found $n)" >&2
        return 2
    fi
    if [ "$(printf '%s\n' "$ids" | sort -u | wc -l)" -ne 1 ]; then
        echo "[build] ERROR: config.xml repositories pin different snapshots: $(printf '%s ' $ids)" >&2
        return 2
    fi
    printf '%s\n' "$ids" | head -n1
}

image_version() {
    sed -n 's|.*<version>\([0-9][0-9.]*\)</version>.*|\1|p' "$HERE/config.xml" | head -n1
}

# write_manifest: the monorepo's commit -- name, commit, clean/DIRTY --
# plus the snapshot id, so a built artifact can be traced to one commit.
# build.sh strips .git during the sync, so this is the only moment the
# commit can be read. "DIRTY" alone cannot distinguish two uncommitted
# states on the same parent, so a dirty tree also records the sha256 of its
# diff against HEAD and the count of untracked files. The repo root must be
# a git checkout whose top level IS that directory (a linked worktree,
# where .git is a file, counts; a plain directory that merely sits inside
# some other repository does not, or the manifest would name a stranger's
# commit) with a 40-hex HEAD. Anything else refuses the sync: a tester
# image that cannot say what went in is not built (round-1 review: a
# worktree was silently stamped "no-git"). Before the monorepo migration
# there was one SOURCE line per sibling repo; now there is exactly one.
repo_head() {
    local dir="$1" top head
    top="$(git -C "$dir" rev-parse --show-toplevel 2>/dev/null)" || return 1
    [ "$(realpath -e -- "$top")" = "$(realpath -e -- "$dir")" ] || return 1
    head="$(git -C "$dir" rev-parse --verify HEAD 2>/dev/null)" || return 1
    [[ "$head" =~ ^[0-9a-f]{40}$ ]] || return 1
    printf '%s\n' "$head"
}
write_manifest() {
    local snap state head status untracked
    snap="$(snapshot_id)" || exit 2
    # Written to a temp name and moved into place: a refusal mid-way must
    # not leave a partial manifest that a later --no-sync would accept.
    rm -f "$MANIFEST" "$MANIFEST.tmp"
    {
        echo "SNAPSHOT=$snap"
        if ! head="$(repo_head "$REPO_ROOT")"; then
            echo "[build] ERROR: $REPO_ROOT is not a git checkout with a commit at HEAD; the image could not say what went in" >&2
            rm -f "$MANIFEST.tmp"
            exit 2
        fi
        # Captured once, and its failure is a failure: piping status into
        # `grep -q` under pipefail returned 141 (SIGPIPE after the first
        # match) on a tree with thousands of untracked files and the
        # else-branch stamped it clean (round-2 review); a git error
        # would have read as clean the same way.
        if ! status="$(git -C "$REPO_ROOT" status --porcelain 2>&1)"; then
            echo "[build] ERROR: git status failed in $REPO_ROOT: $status" >&2
            rm -f "$MANIFEST.tmp"
            exit 2
        fi
        if [ -n "$status" ]; then
            untracked="$(printf '%s\n' "$status" | grep -c '^??' || true)"
            state="DIRTY diff-sha256=$(git -C "$REPO_ROOT" diff HEAD 2>/dev/null | sha256sum | cut -c1-16) untracked=$untracked"
        else
            state=clean
        fi
        printf 'SOURCE %s %s %s\n' qdistro "$head" "$state"
    } > "$MANIFEST.tmp"
    mv "$MANIFEST.tmp" "$MANIFEST"
    echo "[build] source manifest ($MANIFEST):"
    sed 's/^/  /' "$MANIFEST"
}

sync_sources() {
    # qdgreeter + qdlocker are part of the production boot/session path:
    # greetd execs /usr/bin/qdgreeter (greetd-config.toml) and the
    # qdwin-session.target Wants= qdlocker.service. config.sh pip-installs
    # both from this overlay, so they must be present (findings #16, #19).
    local comp
    for comp in $REQUIRED_COMPONENTS; do
        if [ ! -d "$REPO_ROOT/$comp" ]; then
            echo "[build] ERROR: $REPO_ROOT/$comp not found (incomplete monorepo checkout)" >&2
            exit 2
        fi
    done
    # The sync reads its file list from git, so the tree must be its own
    # checkout; write_manifest refuses the same trees, but only after a
    # copy -- refuse before touching the overlay.
    if ! repo_head "$REPO_ROOT" >/dev/null; then
        echo "[build] ERROR: $REPO_ROOT is not a git checkout with a commit at HEAD; the image could not say what went in" >&2
        exit 2
    fi
    # WHAT is copied: the source as git sees it -- every tracked file plus
    # every untracked file that is not ignored (what `git add -A` would
    # stage), and nothing else. An exclude list could only ever name the
    # debris somebody had already noticed: the rsync-with-excludes this
    # replaces still shipped qdwin/build-qci/ and qdshell/build-qci/ (meson
    # dirs with host-built binaries), .mypy_cache/, .pytest_cache/,
    # .hypothesis/, .ruff_cache/, .coverage-report.json, extension dist/ and
    # coverage/, qdshell/tests/ui/artifacts/, *.egg-info -- and would have
    # shipped image/keys/ (gitignored signing material) had it existed.
    # Everything is gitignored for a reason; .gitignore is the maintained
    # list of "not source". Untracked-but-not-ignored files ARE copied: a
    # dirty dev build must contain the new file the manifest counts in
    # `untracked=N`. Nothing the image builds from is generated on the
    # host: config.sh runs meson from scratch (`setup build --wipe`),
    # browser extensions are staged from source with dist/ and
    # node_modules/ stripped, qsu is compiled in the chroot.
    #   Belt and braces, whatever git says: never the overlay itself
    #   (image/root/root -- it is inside the repo), linked worktrees, CI
    #   run artifacts, build logs, or key material.
    #   A path ending in `/` is an untracked nested git repository (git
    #   lists it as a unit); it is not source of this repo, skip it.
    #   A tracked path deleted in the working tree is skipped, not an
    #   rsync error (the manifest records the tree as DIRTY).
    local list path n=0
    # Outside the overlay tree (image/root/ is copied into the image).
    list="$(mktemp "${TMPDIR:-/tmp}/qdistro-src-files.XXXXXX")"
    if ! git -C "$REPO_ROOT" ls-files -z --cached --others --exclude-standard \
            > "$list.raw"; then
        echo "[build] ERROR: git ls-files failed in $REPO_ROOT" >&2
        rm -f "$list" "$list.raw"
        exit 2
    fi
    # Sorted as its own checked step: a failure inside a `< <(...)`
    # process substitution is invisible to set -e and pipefail, and an
    # empty list would wipe the overlay and stamp the manifest clean
    # (fu review: a failing `sort -zu` synced 0 files with exit 0).
    if ! sort -zu -o "$list.raw" "$list.raw"; then
        echo "[build] ERROR: sorting the git file list failed" >&2
        rm -f "$list" "$list.raw"
        exit 2
    fi
    while IFS= read -r -d '' path; do
        case "$path" in
            */) echo "[build] skipping untracked nested repository $path" >&2; continue ;;
            image/root/root|image/root/root/*|.worktrees|.worktrees/*|ci/runs|ci/runs/*|\
            image/logs|image/logs/*|image/keys|image/keys/*|.git|.git/*) continue ;;
        esac
        [ -e "$REPO_ROOT/$path" ] || [ -L "$REPO_ROOT/$path" ] || continue
        printf '%s\0' "$path"
        n=$((n + 1))
    done < "$list.raw" > "$list"
    rm -f "$list.raw"
    # A fresh overlay every time: rsync --files-from cannot --delete, and
    # the overlay is a generated, gitignored copy. This also clears debris
    # of any earlier sync (the pre-monorepo per-repo qdistro/ copy, the
    # unfiltered syncs that nested image/root/root and image/logs).
    rm -rf "$SRC_OVERLAY"
    install -d -m 0755 "$SRC_OVERLAY"
    echo "[build] copying $n git-visible files of $REPO_ROOT -> $SRC_OVERLAY"
    if ! rsync -a --from0 --files-from="$list" "$REPO_ROOT/" "$SRC_OVERLAY/"; then
        echo "[build] ERROR: rsync of the source tree failed" >&2
        rm -f "$list"
        exit 2
    fi
    rm -f "$list"
    echo "[build] source overlay size:"
    du -sh "$SRC_OVERLAY" 2>&1 | sed 's/^/  /'
    write_manifest
}

case "${1:-}" in
  --clean)
    rm -rf "$BUILD_DIR"
    rm -rf "$HERE/root/root"
    sync_sources
    ;;
  --sync-only)
    sync_sources
    exit 0
    ;;
  --no-sync)
    # Sources are already present (e.g. baked into a VM by build-in-vm.sh).
    # The manifest is written at sync time, on the host; without it the
    # image could not say what went in, so its absence is a build error.
    if [ ! -s "$MANIFEST" ]; then
        echo "[build] ERROR: --no-sync but no source manifest at $MANIFEST (run --sync-only first)" >&2
        exit 2
    fi
    ;;
  --snapshot-id)
    snapshot_id
    exit $?
    ;;
  --test)
    img=$(find "$BUILD_DIR" -maxdepth 1 -name '*.raw' 2>/dev/null | head -1)
    [ -n "$img" ] || { echo "no .raw image in $BUILD_DIR; run a build first" >&2; exit 1; }
    OVMF=""
    for c in /usr/share/qemu/ovmf-x86_64.bin /usr/share/qemu/ovmf-x86_64-code.bin /usr/share/OVMF/OVMF_CODE.fd; do
        [ -f "$c" ] && OVMF="$c" && break
    done
    [ -n "$OVMF" ] || { echo "no OVMF firmware found" >&2; exit 1; }
    exec qemu-system-x86_64 -enable-kvm -m 4096 -smp 2 \
      -bios "$OVMF" \
      -drive file="$img",format=raw,if=virtio \
      -netdev user,id=n0 -device virtio-net,netdev=n0
    ;;
  "")
    sync_sources
    ;;
  *)
    echo "unknown arg: $1" >&2
    exit 2
    ;;
esac

if [ "$EUID" -ne 0 ]; then
  echo "[build] build must run as root; re-exec with sudo" >&2
  exec sudo -E "$0" "$@"
fi

mkdir -p "$BUILD_DIR"
SNAPSHOT="$(snapshot_id)" || exit 2
VERSION="$(image_version)"
[ -n "$VERSION" ] || { echo "[build] ERROR: no <version> in config.xml" >&2; exit 2; }
if ! grep -q "^SNAPSHOT=$SNAPSHOT\$" "$MANIFEST"; then
    echo "[build] ERROR: manifest snapshot ($(sed -n 's/^SNAPSHOT=//p' "$MANIFEST")) != config.xml snapshot ($SNAPSHOT); re-sync" >&2
    exit 2
fi

KIWI_PROFILE_ARGS=()
case "${QDISTRO_KIWI_PROFILE:-tester}" in
    tester) ;;
    ci) KIWI_PROFILE_ARGS+=(--profile ci) ;;
    *) echo "[build] ERROR: QDISTRO_KIWI_PROFILE must be tester or ci, got: ${QDISTRO_KIWI_PROFILE}" >&2; exit 2 ;;
esac

echo "[build] kiwi-ng building OEM image $VERSION on Tumbleweed $SNAPSHOT -> $BUILD_DIR (kiwi profile ${QDISTRO_KIWI_PROFILE:-tester})"
mkdir -p "$HERE/logs"
kiwi-ng --debug \
  "${KIWI_PROFILE_ARGS[@]}" \
  --type oem \
  system build \
    --description "$HERE" \
    --target-dir "$BUILD_DIR" \
  2>&1 | tee "$HERE/logs/kiwi-build.log"
# `set -o pipefail` above: a kiwi failure is this script's failure.

# Release artifact. kiwi's `compressed` attribute is valid only for pxe/kis
# types (schema 8.4), so an OEM build cannot emit .raw.xz itself; `result
# bundle` copies the results under bundle/ (reflink/sparse cp), xz-compresses
# the raw with --threads=0 and writes a .sha256 of the compressed file. With
# bundle_format="%N-%v-%I" in config.xml the name is <name>-<version>-<id>;
# the id is the snapshot so the filename says what it was built on.
BUNDLE_DIR="$BUILD_DIR/bundle"
rm -rf "$BUNDLE_DIR"
echo "[build] bundling -> $BUNDLE_DIR (xz of the raw; several minutes)"
kiwi-ng result bundle \
    --target-dir "$BUILD_DIR" \
    --id "$SNAPSHOT" \
    --bundle-dir "$BUNDLE_DIR" \
  2>&1 | tee "$HERE/logs/kiwi-bundle.log"
XZ="$BUNDLE_DIR/qdistro-$VERSION-$SNAPSHOT.raw.xz"
[ -f "$XZ" ] || { echo "[build] ERROR: bundle did not produce $XZ" >&2; ls -l "$BUNDLE_DIR" >&2; exit 1; }
[ -f "$XZ.sha256" ] || { echo "[build] ERROR: bundle did not produce $XZ.sha256" >&2; exit 1; }

echo
echo "[build] artifacts:"
ls -lh "$BUILD_DIR" "$BUNDLE_DIR" | grep -E '\.(raw|iso|qcow2|xz|sha256)$' || true
